[package]
name = "file-playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# dependencies for convert base64 & image

base64 = "0.21.0"
image = "0.24.6"